spring.application.name=moneyLoverDataManager
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
springdoc.api-docs.path=/api-docs

spring.datasource.url=jdbc:postgresql://localhost:5432/business_db
spring.datasource.username=postgres
spring.datasource.password=moneylover
spring.sql.init.mode=always
spring.datasource.initialize=true
spring.sql.init.continue-on-error=false

spring.datasource.hikari.maximum-pool-size=80
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true 

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect



